# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               期望最大化（洪亮劼的专栏）
tagline:             '分享技术、管理、团队和业界的思考'
description:         'Nokia全球副总裁、前LinkedIn工程总监、前Etsy工程总监、雅虎研究院高级研发经理；长期从事人工智能和机器学习在工业界广泛落地的研究和实践工作；这是一个分享技术、管理、团队和业界思考的专栏。'
url:                 http://column.hongliangjie.com
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              洪亮劼
  url:               https://www.hongliangjie.com
  email:             hongliangjie@gmail.com

# Custom vars
version:             1.0.0

plugins:
  - jekyll-sitemap
